services:
  postgres-dev-animes-api:
    image: postgres:18
    container_name: api-animes-teste-postgres-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U postgres -d postgres',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local